roslaunch turtlebot3_gazebo tutlebot3_empty_world.launch
roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch
roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch
roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch
rosrun forward_backward.py
rosrun prrexamples  forward_backward.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  dance.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance
rosrun prrexamples  dance.py
rosrun prrexamples dance.py
rosrun prrexamples dance.py
rosrun prrexamples dance.py
rosrun prrexamples dance.py
clear
clear
rosrun prrexamples dance.py
rosrun prrexamples dance.py
rosrun prrexamples dance.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples key_publisher.py
rosrun prrexamples key_publisher.py
rosrun prrexamples key_publisher.py
:]~$ rosrun prrexamples dance.py
[rosrun] Couldn't find executable named dance.py below /my_ros_data/catkin_ws/src/prrexamples
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /my_ros_data/catkin_ws/src/prrexamples/src/dance.py
rosrun prrexamples key_publisher.py
rosrun prrexamples key_publisher.py
rosrun prrexamples key_publisher.py
rosrun prrexamples dance.py
rosrun prrexamples dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  forwards_backwards.py
rosrun prrexamples  dance_pa_starter.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
chmod +x dancy.py
chmod +x dance.py
chmod +x /my_ros_data/catkin_ws/src/prrexamples/src/dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples key_publisher.py
rosrun prrexamples key_publisher.py
rosmsg show sensor_msgs/LaserScan
roslaunch laser_values laser.launch
chmod +x src/scan.py
chmod +x scan.py
chmod +x  scan.py
rosrun prrexamples key_publisher.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples  dance.py
rosrun prrexamples scan_values_handler.py
chmod +x /my_ros_data/catkin_ws/src/prrexamples/src/pa_starters/wall_follower/src/scan_values_handler.py
rosrun prrexamples scan_values_handler.py
rosrun prrexamples scan_values_handler.py
rosrun prrexamples scan_values_handler.py
rosrun prrexamples scan_values_handler.py
roslaunch prrexamples wall_follower.launch
rosrun prrexamples scan_values_handler.py
rosrun prrexamples scan_values_handler.py
rosrun prrexamples scan_values_handler.py
rosrun prrexamples scan_values_handler.py
rostopic echo /kobuki/lase/scan -n1
rostopic echo /kobuki/laser/scan -n1
rostopic list
rostopic echo /scan
rostopic echo /scan
rostopic echo /scan
roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch
roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch
roslaunch gazebo_ros _stage_1.launch
roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch
roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch
catkin_create_pkg
catkin_create_pkg pa1
rosrun prrexamples key_publisher.py
roslaunch laser_values laser.launchroslaunch turtlebot3_gazebo turtlebot3_stage_1.launch
